### ISSUE TITLE
Compiling and evaluating variable assignment

### ISSUE THREAD

**Issue by emilywoods** [emilywoods/emerald#14]
*Local variables*
Input lisp:
```lisp
(let [x (+ 1 2) ] )
```
compiles to:
```ruby
x = 1 + 2
```
which evaluates to:
```
3
```

*Global variables*
Input lisp:
```lisp
(def input "Hello")
```
compiles to:
```ruby
$input = "Hello"
```
which evaluates to:
```
"Hello"
```

**Comment by lpil** [comment]
For the let you may want to think a bit about limiting the scope of the variable.

```lisp
(let [x 1]
  x + x)
x
```

This should error at the end as `x` is undefined, however it would not error if we compiled it to this ruby:

```ruby
x = 1
x + x
x
```

Instead we might want something like this

```ruby
begin
  x = 1
  x + x
end
x
```

**Comment by emilywoods** [comment]
Noted. :) 👍
